ALTER TABLE p2p_industryclassi MODIFY ClassiName_CN varchar(128) DEFAULT NULL;
UPDATE p2p_industryclassi SET ClassiName_CN = 'Agriculture, forestry, husbandry and fishery' WHERE IndustryNum = 'A';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Mining Industry' WHERE IndustryNum = 'B';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Manufacturing industry' WHERE IndustryNum = 'C';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Industry of electricity, heating power, gas and water production and supply' WHERE IndustryNum = 'D';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Construction industry' WHERE IndustryNum = 'E';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Wholesale and retail sales' WHERE IndustryNum = 'F';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Transportation, warehousing and postal service' WHERE IndustryNum = 'G';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Hotels and Catering Services' WHERE IndustryNum = 'H';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Information transmission, software and information technology services' WHERE IndustryNum = 'I';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Financial industry' WHERE IndustryNum = 'J';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Real estate industry' WHERE IndustryNum = 'K';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Leasing and business services' WHERE IndustryNum = 'L';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Scientific research and technical services' WHERE IndustryNum = 'M';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Water conservation, environment and public facilities management' WHERE IndustryNum = 'N';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Education' WHERE IndustryNum = 'P';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Health care and social work' WHERE IndustryNum = 'Q';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Culture, Sports and Entertainment' WHERE IndustryNum = 'R';
UPDATE p2p_industryclassi SET ClassiName_CN = 'Integrated industries' WHERE IndustryNum = 'S';